package io.kestra.plugin.datagen.core;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.MappingIterator;
import com.fasterxml.jackson.databind.SequenceWriter;
import io.kestra.core.models.annotations.Example;
import io.kestra.core.models.annotations.Plugin;
import io.kestra.core.models.annotations.PluginProperty;
import io.kestra.core.models.property.Property;
import io.kestra.core.models.tasks.Output;
import io.kestra.core.models.tasks.RunnableTask;
import io.kestra.core.models.tasks.Task;
import io.kestra.core.runners.RunContext;
import io.kestra.core.serializers.JacksonMapper;
import io.kestra.plugin.datagen.internal.Fakers;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import lombok.experimental.SuperBuilder;
import net.datafaker.Faker;

import java.io.*;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.*;

@Plugin(
    examples = {
        @Example(
            full = true,
            code = """
            id: anonymize_csv
            namespace: company.team

            tasks:
              - id: anonymize
                type: io.kestra.plugin.datagen.core.Anonymize
                from: "{{ inputs.file }}"
                contentType: CSV
                fields:
                  name: "#{name.fullName}"
                  email: "#{internet.emailAddress}"
            """
        ),
        @Example(
            full = true,
            code = """
            id: anonymize_json
            namespace: company.team

            tasks:
              - id: anonymize
                type: io.kestra.plugin.datagen.core.Anonymize
                from: "{{ inputs.file }}"
                contentType: JSON
                fields:
                  user.profile.email: "#{internet.emailAddress}"
                  user.profile.name: "#{name.fullName}"
                  user.address.city: "#{address.city}"
            """
        ),
        @Example(
            full = true,
            code = """
            id: anonymize_csv_with_locale
            namespace: company.team

            tasks:
              - id: anonymize
                type: io.kestra.plugin.datagen.core.Anonymize
                from: "{{ inputs.file }}"
                contentType: CSV
                locale: ["fr", "FR"]
                fields:
                  nom: "#{name.fullName}"
                  email: "#{internet.emailAddress}"
                  ville: "#{address.city}"
            """
        ),
        @Example(
            full = true,
            code = """
            id: anonymize_json_autodetect
            namespace: company.team

            tasks:
              - id: generate
                type: io.kestra.plugin.datagen.core.Generate
                batchSize: 50
                store: true
                generator:
                  type: io.kestra.plugin.datagen.generators.JsonObjectGenerator
                  value:
                    name: "#{name.fullName}"
                    email: "#{internet.emailAddress}"
                    age: 30

              - id: anonymize
                type: io.kestra.plugin.datagen.core.Anonymize
                from: "{{ outputs.generate.uri }}"
                contentType: JSON
                fields:
                  name: "#{name.fullName}"
                  email: "#{internet.emailAddress}"
            """
        )
    }
)
@Schema(
    title = "Anonymize fields in a CSV or JSON file",
    description = """
        Reads a CSV or JSON file from Kestra internal storage, replaces the specified fields
        with realistic fake values generated by [Datafaker](https://www.datafaker.net/documentation/expressions/),
        and writes the anonymized result back to internal storage.

        For JSON files, dot-notation paths (e.g. `user.profile.email`) address nested fields.
        For CSV files, only flat column names are supported. Paths that do not exist in a record
        are silently skipped — the record is written as-is. Fields not listed in `fields` are
        preserved verbatim.
        """
)
@SuperBuilder
@ToString
@EqualsAndHashCode
@Getter
@NoArgsConstructor
public class Anonymize extends Task implements RunnableTask<Anonymize.AnonymizeOutput> {

    @Schema(
        title = "Input file URI",
        description = "URI of the file in Kestra internal storage to anonymize."
    )
    @NotNull
    @PluginProperty(group = "source")
    private Property<String> from;

    @Schema(
        title = "Fields to anonymize",
        description = """
            Map of field paths to Datafaker expressions. For JSON, dot-notation paths (e.g.
            `user.profile.email`) address nested structures. For CSV, flat column names are used.
            Fields absent from this map are preserved verbatim.
            """
    )
    @PluginProperty(group = "main")
    private Property<Map<String, String>> fields;

    @Schema(
        title = "Content type",
        description = "Input (and output) format: `CSV` or `JSON`. When absent, auto-detected from the file extension (`.csv` or `.json`)."
    )
    @PluginProperty(group = "main")
    private Property<ContentType> contentType;

    @Schema(
        title = "Locales",
        description = "Optional Faker locale list in the format `[language]`, `[language, country]`, or `[language, country, variant]`. Defaults to Faker's built-in locale when omitted."
    )
    @PluginProperty(group = "advanced")
    private Property<List<String>> locale;

    @Override
    public AnonymizeOutput run(RunContext runContext) throws Exception {
        var rFrom = runContext.render(this.from).as(String.class).orElseThrow();
        var rFields = runContext.render(this.fields).asMap(String.class, String.class);
        var rLocale = runContext.render(this.locale).asList(String.class);

        var faker = Fakers.create(rLocale);
        var inputUri = URI.create(rFrom);
        var resolvedContentType = resolveContentType(runContext, inputUri);

        var tempFile = runContext.workingDir().createTempFile(resolvedContentType == ContentType.CSV ? ".csv" : ".json").toFile();
        long count;

        try (var inputStream = runContext.storage().getFile(inputUri)) {
            count = switch (resolvedContentType) {
                case CSV -> processCsv(inputStream, tempFile, faker, rFields, runContext);
                case JSON -> processJson(inputStream, tempFile, faker, rFields);
            };
        }

        var outputUri = runContext.storage().putFile(tempFile);
        runContext.logger().info("Anonymized {} record(s) written to {}", count, outputUri);

        return AnonymizeOutput.builder()
            .uri(outputUri)
            .count(count)
            .build();
    }

    private ContentType resolveContentType(RunContext runContext, URI inputUri) throws Exception {
        if (this.contentType != null) {
            return runContext.render(this.contentType).as(ContentType.class).orElseThrow();
        }
        var path = inputUri.getPath().toLowerCase(Locale.ROOT);
        if (path.endsWith(".csv")) {
            return ContentType.CSV;
        } else if (path.endsWith(".json") || path.endsWith(".ion")) {
            return ContentType.JSON;
        }
        throw new IllegalArgumentException(
            "Cannot auto-detect content type from URI '%s'. Set the 'contentType' property explicitly.".formatted(inputUri)
        );
    }

    private long processCsv(
        InputStream inputStream,
        File outputFile,
        Faker faker,
        Map<String, String> fields,
        RunContext runContext
    ) throws IOException {
        try (
            var reader = new BufferedReader(new InputStreamReader(inputStream, StandardCharsets.UTF_8));
            var writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(outputFile), StandardCharsets.UTF_8))
        ) {
            var headerLine = reader.readLine();
            if (headerLine == null) {
                return 0L;
            }

            var headers = parseCsvLine(headerLine);
            writer.write(headerLine);
            writer.newLine();

            long count = 0L;
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.isBlank()) {
                    continue;
                }
                var values = parseCsvLine(line);
                // extend values array to match header length if needed
                var record = new ArrayList<>(values);
                while (record.size() < headers.size()) {
                    record.add("");
                }

                for (var entry : fields.entrySet()) {
                    var key = entry.getKey();
                    var idx = headers.indexOf(key);
                    if (idx >= 0 && idx < record.size()) {
                        record.set(idx, Fakers.evaluate(faker, entry.getValue()));
                    }
                }

                writer.write(buildCsvLine(record));
                writer.newLine();
                count++;
            }
            return count;
        }
    }

    private long processJson(
        InputStream inputStream,
        File outputFile,
        Faker faker,
        Map<String, String> fields
    ) throws IOException {
        var mapper = JacksonMapper.ofJson(false);
        var mapType = new TypeReference<Map<String, Object>>() {};

        try (
            var reader = new BufferedReader(new InputStreamReader(inputStream, StandardCharsets.UTF_8));
            var outputStream = new FileOutputStream(outputFile);
            var writer = new BufferedWriter(new OutputStreamWriter(outputStream, StandardCharsets.UTF_8))
        ) {
            long count = 0L;
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.isBlank()) {
                    continue;
                }
                // Strip Ion type annotations if present (e.g. produced by Generate with store=true)
                var jsonLine = stripIonAnnotation(line);

                Map<String, Object> record;
                try {
                    record = mapper.readValue(jsonLine, mapType);
                } catch (Exception e) {
                    // Not parseable as JSON object; skip silently
                    writer.write(line);
                    writer.newLine();
                    count++;
                    continue;
                }

                for (var entry : fields.entrySet()) {
                    applyDotPath(record, entry.getKey(), faker, entry.getValue());
                }

                writer.write(mapper.writeValueAsString(record));
                writer.newLine();
                count++;
            }
            return count;
        }
    }

    /**
     * Strips a leading Ion type annotation (e.g. {@code 'net.datafaker.Faker'::{...}} → {@code {...}})
     * so Ion-serialized lines produced by Generate can be parsed as plain JSON.
     */
    private static String stripIonAnnotation(String line) {
        var trimmed = line.trim();
        // Ion annotations end with "::" before the actual value
        int annotationEnd = trimmed.indexOf("::{");
        if (annotationEnd >= 0) {
            return trimmed.substring(annotationEnd + 2);
        }
        return trimmed;
    }

    @SuppressWarnings("unchecked")
    private static void applyDotPath(Map<String, Object> record, String dotPath, Faker faker, String expression) {
        var parts = dotPath.split("\\.", -1);
        Map<String, Object> current = record;

        for (int i = 0; i < parts.length - 1; i++) {
            var next = current.get(parts[i]);
            if (!(next instanceof Map)) {
                // Intermediate node missing or not a map: silently skip
                return;
            }
            current = (Map<String, Object>) next;
        }

        var leaf = parts[parts.length - 1];
        if (current.containsKey(leaf)) {
            current.put(leaf, Fakers.evaluate(faker, expression));
        }
        // Key absent at leaf: silently skip
    }

    // --- CSV helpers ---

    private static List<String> parseCsvLine(String line) {
        var result = new ArrayList<String>();
        var sb = new StringBuilder();
        var inQuotes = false;

        for (int i = 0; i < line.length(); i++) {
            var ch = line.charAt(i);
            if (ch == '"') {
                if (inQuotes && i + 1 < line.length() && line.charAt(i + 1) == '"') {
                    // Escaped quote
                    sb.append('"');
                    i++;
                } else {
                    inQuotes = !inQuotes;
                }
            } else if (ch == ',' && !inQuotes) {
                result.add(sb.toString());
                sb.setLength(0);
            } else {
                sb.append(ch);
            }
        }
        result.add(sb.toString());
        return result;
    }

    private static String buildCsvLine(List<String> values) {
        var sb = new StringBuilder();
        for (int i = 0; i < values.size(); i++) {
            if (i > 0) sb.append(',');
            var val = values.get(i);
            if (val.contains(",") || val.contains("\"") || val.contains("\n")) {
                sb.append('"').append(val.replace("\"", "\"\"")).append('"');
            } else {
                sb.append(val);
            }
        }
        return sb.toString();
    }

    // --- Inner types ---

    public enum ContentType {
        CSV,
        JSON
    }

    @Schema(title = "Anonymize task output")
    @Builder
    @Getter
    public static class AnonymizeOutput implements Output {

        @Schema(
            title = "Output file URI",
            description = "URI of the anonymized file in Kestra internal storage."
        )
        @PluginProperty(group = "destination")
        private final URI uri;

        @Schema(
            title = "Records processed",
            description = "Number of records read and written (including records where no field was replaced)."
        )
        @PluginProperty(group = "execution")
        private final long count;
    }
}
