package io.kestra.plugin.datagen;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;

import java.net.URI;

@AllArgsConstructor
@Getter
@Builder
public class Data implements io.kestra.core.models.tasks.Output {

    @Schema(
        title = "Size of the generated data",
        description = "The total size in bytes of the generated data value or file."
    )
    private Long size;

    @Schema(
        title = "Total number of the generated items",
        description = "The total number of items generated by the task."
    )
    private Integer count;

    @Schema(
        title = "Generated data value",
        description = "The actual content of the generated data. This can be a string, number, JSON object, or binary payload depending on the generator configuration."
    )
    private final Object value;

    @Schema(
        title = "The generated file URI."
    )
    private final URI uri;
}
